apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: github-proxy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: github.isitup.fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: github-proxy
          servicePort: 80
        path: /
  tls:
  - hosts:
    - github.isitup.fuchicorp.com
    secretName: proxy-proxy-tls